# Generated by Django 4.0.3 on 2022-09-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_restaurantinfo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutinfo',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='aboutinfo',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='aboutinfo',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='subject',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='restaurantinfo',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='restaurantinfo',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='restaurantinfo',
            name='email',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='restaurantinfo',
            name='hours',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='restaurantinfo',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='restaurantinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
