# Generated by Django 4.0.3 on 2022-09-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_alter_aboutinfo_description_alter_aboutinfo_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comingsoon',
            name='image',
            field=models.ImageField(upload_to='ComingSoon/'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(upload_to='MenuItem/'),
        ),
    ]
