# Generated by Django 4.0.3 on 2022-09-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_alter_comingsoon_image_alter_menuitem_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('review', models.TextField()),
                ('star_nbr', models.IntegerField()),
                ('image', models.ImageField(blank=True, upload_to='reviews/')),
            ],
        ),
    ]
