# Generated by Django 4.0.3 on 2022-09-14 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_alter_clientreview_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientreview',
            name='image',
        ),
    ]
