# Generated by Django 4.0.3 on 2022-09-14 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_remove_clientreview_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comingsoon',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.menucategory'),
        ),
    ]
